////
This document is maintained in the main Quarkus repository, and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
[id="security-identity-providers"]
= Identity providers
include::_attributes.adoc[]
:diataxis-type: concept
:categories: security
:topics: security,identity-providers
:extensions: io.quarkus:quarkus-elytron-security-jdbc,io.quarkus:quarkus-elytron-security-ldap,io.quarkus:quarkus-security-jpa-reactive


In the Quarkus Security framework, identity providers play a crucial role in authentication and authorization by verifying user identities.
`IdentityProvider` creates a `SecurityIdentity` instance, which gets used during user authentication to verify and authorize access requests to your Quarkus application.

[id="identity-providers"]
`IdentityProvider` converts the authentication credentials provided by `HttpAuthenticationMechanism` to a `SecurityIdentity` instance.

Some extensions, for example, `OIDC`, `OAuth2`, and `SmallRye JWT`, have inline `IdentityProvider` implementations specific to the supported authentication flow.
For example, `quarkus-oidc` uses its own `IdentityProvider` to convert a token to a `SecurityIdentity` instance.

If you use Basic or form-based authentication, you must add an `IdentityProvider` instance to convert a username and password to a `SecurityIdentity` instance.

To get started with security in Quarkus, consider combining the Quarkus built-in Basic HTTP authentication with the Jakarta Persistence identity provider to enable role-based access control (RBAC).

For more information about Basic authentication, its mechanisms, and related identity providers, see the following resources:

* link:{default-url}/getting-started-with-security/security-jpa[Quarkus Security with Jakarta Persistence]
** link:{default-url}/getting-started-with-security/security-getting-started-tutorial[Getting started with Security by using Basic authentication and Jakarta Persistence]
* link:{default-url}/security-architecture/security-authentication-mechanisms#form-auth[Form-based authentication]
* link:{quarkusio-guides}/security-jdbc[Using security with JDBC]
* link:{quarkusio-guides}/security-ldap[Using security with an LDAP realm]
* link:{default-url}/security-overview/security-overview[Quarkus Security overview]
